language: node_js
node_js:
  - "10.14" # node_js에 버전 10.14.1

# Git 커밋을 한 내용중 수신 허용 목록을
# 사용하여 분기를 포함하거나 차단 목록을 사용하여 분기를 제외하십시오.
branches:
  # safelist
  only:
    - master

cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - mins5190@gmail.com