language: node_js
node_js:
  - "10.14" # node_js에 버전 10.14.1

# Jest에서 사용하는 테스트 코드는 graphql 사용시 
# postgresql을 같이 사용하기 때문에 이용
#services:
#    postgresql: "10"

# 로컬 postgresql 서버에 엑세스하기 위해서 작성
# 응용 프로그램의 데이터베이스를 만듭니다.
#before_script:
#  - psql -c 'create database test_creatix;' -U postgres

# Git 커밋을 한 내용중 수신 허용 목록을
# 사용하여 분기를 포함하거나 차단 목록을 사용하여 분기를 제외하십시오.
branches:
  # safelist
  only:
    - master

# Travis CI는 자주 변경되지 않는 컨텐츠를 캐시하여 빌드 프로세스의 속도를 높일 수 있습니다.
# 캐싱 기능을 사용하려면 저장소 설정에서 Build Bushed Branch를 ON으로 설정하십시오.
cache:
  directories:
    - "node_modules"

script:
  - npm test

# 빌드 성공및 실패에 대한 알림을 받을 이메일
notifications:
  email:
    recipients:
      - mins5190@gmail.com