language: node_js
node_js:
  - "10.14" # node_js에 버전 10.14.1

// 환경 변수 설정
env:
  - EMAIL=$EMAIL
  - PASS=$PASS

# Git 커밋을 한 내용중 수신 허용 목록을
# 사용하여 분기를 포함하거나 차단 목록을 사용하여 분기를 제외하십시오.
branches:
  # safelist
  only:
    - master

# Travis CI는 자주 변경되지 않는 컨텐츠를 캐시하여 빌드 프로세스의 속도를 높일 수 있습니다.
# 캐싱 기능을 사용하려면 저장소 설정에서 Build Bushed Branch를 ON으로 설정하십시오.
cache:
  directories:
    - "node_modules"

script:
  - npm test

# 빌드 성공및 실패에 대한 알림을 받을 이메일
notifications:
  email:
    recipients:
      - mins5190@gmail.com